### ISSUE TITLE
"Advanced" header use of colspan throws off position calculations

### ISSUE THREAD

**Issue by mike-north** [DataTables/ColReorder#12]
#### Overview

The documentation here (http://datatables.net/examples/advanced_init/complex_header.html) recommends the usage of rowspan and colspan to create groups of columns in an "advanced header".

Combining this with the ColReorder plugin can result in some unexpected behavior
#### Live Demo

[http://live.datatables.net/ugukul/5](http://live.datatables.net/ugukul/5)
#### Steps to reproduce
1. Drag "Browser" column all the way to the right -- _everything is as expected, no console errors are shown_
2. Attempt to put the "Browser" column back when it originally was (2nd from the left), and you'll get the following error

```
Uncaught NotFoundError: 
An attempt was made to reference a Node in a context where it does not exist.
```

**Comment by TJ-Compton** [comment]
Have you given any further consideration to adding support for, at least, td/th with colspan=the total number of columns in the table (since that would just involve skipping that tr)?
It would be really great to be able to use full-width header and footer rows again without breaking ColReorder.
Also, is there any mention of the col/rowspan restriction(s) in the documentation? If so, I couldn't find it, and I spent quite a while trying to figure out what was going on to only allow my first column to be reordered. Maybe a more prominent notice would be appropriate :)

**Comment by DataTables** [comment]
I haven't had a chance to do any work on this recently I'm afraid, as I've been working on other aspects of DataTables. Ultimately it would be good to have this, but it hasn't been implemented yet.

**Comment by TJ-Compton** [comment]
I've made a pull request for a small tweak that allows simple colspan setups (particularly one-item rows) to work without interfering in the operation of the plugin. It'll still break under complex configurations, but in my opinion, limited functionality is better than no functionality.
