### ISSUE TITLE
_fnCreateDragNode and styling

### ISSUE THREAD

**Issue by ksiegel** [DataTables/ColReorder#23]
I have my datatable in a div where `font-size: .75em`, so when `_fnCreateDragNode` creates the node in `body`, it appears 25% larger than how it appears in the table. 

Should `_fnCreateDragNode` create the clone in `oInstance.parent` to ensure styling stays consistent? I did a dry run and tried it locally, but it seems that there's a lot of positioning that would need to be rewritten. My temporary solution is `.DTCR_clonedTable{font-size: .75em;}`, but other folks with other styling may not have it that easy. 

I also find that the DOM cloning going on there is a little funny. It's skipping inserting the `thead`, which is what actually gives the `th` its styling in the DataTables CSS. This is because `appendChild` returns the child itself, so the `thead` isn't ever actually returned to be added. This is easily solved by adding `.parentElement`: (around line 1050) `.append(origThead.cloneNode(false).appendChild(...).parentElement)`

I'll submit a pull request based on your feedback with the whole positioning rewrite, or any reasoning why it's put in body instead of `oInstance.parent`

p.s. any word on the whereabouts of a ColReorderWithResize.js? I was comparing the old one to the new ColReorder.js and considering porting over the resize ability.

**Comment by DataTables** [comment]
Hi,

Sorry for the massive delay in replying to this! I think you are correct, there would need to be a lot of consideration for position if the clone were attached anywhere other than to the `body`. I feel that any code there would be significantly more complex that simply adding a CSS rule. It isn't ideal I realise, but probably the best option at the moment.

> This is because appendChild returns the child itself

Well damn - I hadn't clocked that! Fixed in f9f64f9b8e.

> p.s. any word on the whereabouts of a ColReorderWithResize.js? I was comparing the old one to the new ColReorder.js and considering porting over the resize ability.

If you really wanted Resizing, I would suggest foregoing ColReorderWithResize and a new plug-in should be created. It was a 3rd party hack.
