### ISSUE TITLE
Missing build output in releases

### ISSUE THREAD

**Issue by arthot** [DataTables/ColReorder#48]
Using ColReorder via bower is impossible without scss compilation.
I think to have a directory 'dist' with already precompiled css/js is good practice.

**Comment by DataTables** [comment]
I'm actually just about to start work on resolving this. I'm going to need to create distribution repos rather than just a directory in this repo since there are multiple styling options and that appears to be the best way to handle it for NPM. I'll leave this open until done and post back when finished.

**Comment by DataTables** [comment]
DataTables has [distribution packages now](http://datatables.net/blog/2015-11-09) which you can read about in the DataTables blog.
