### ISSUE TITLE
Specify source repository for NPM package

### ISSUE THREAD

**Issue by ceefour** [DataTables/ColReorder#56]
Deploying to http://www.webjars.org/npm gives the following error:

```
Failed!
The source repository for datatables.net-colreorder 1.3.1 could not be determined but is required to published to Maven Central.  This will need to be fixed in the project's package metadata.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: datatables.net-colreorder
Starting Deploy
```

**Comment by DataTables** [comment]
I've just committed the changes required to the distribution repos to add the `repository` attribute in package.json. However, as far as I am aware, in order for npm to actually see that update a new release needs to be made (delighted to be proven wrong there if you or anyone else knows otherwise).

I'm not planning on making any releases this week and probably not next.
