### ISSUE TITLE
Support for enabling via class helper and support for Responsive plugin

### ISSUE THREAD

**Issue by dswitzer** [DataTables/ColReorder#72]
This is a minor enhancement to the `preInit.dt` event to add:

* Support for enabling the plugin via CSS (via `dt-colreorder` class)
* A hack for use with the responsive plugin

The solution for using ColReorder with the responsive plugin needs to be better, but this works for our use case. We trigger the `Responsive` plugin via CSS, so I need a way for the `ColReorder` to prevent dragging that element around because the Responsive plugin if the column moves.

```
$(document).on( 'preInit.dt.colReorder', function (e, settings) {
	if ( e.namespace !== 'dt' ) {
		return;
	}

	var init = settings.oInit.colReorder;
	var defaults = DataTable.defaults.colReorder;

	/*
	 * We want to check if the dt-colReorder has been supplied, which enables the reordering
	 */
	if( init || defaults || $(settings.nTable).hasClass('dt-colreorder') ){
		var opts = $.extend({}, init, defaults);

		/*
		 * If the Responsive plugin is enabled, we need to disable re-ordering the first column.
		 */
		if( settings.responsive ){
			// if we already have a fixedColumnLeft argument, then do not override
			if( !("fixedColumnsLeft" in opts) ){
				opts.fixedColumnsLeft = 1;
			}
		}

		if ( init !== false ) {
			new DataTable.ColReorder(settings, opts);
		}
	}
});
```

**Comment by DataTables** [comment]
Thanks for this! I've actually intentionally been stepping away from enabling extensions / features using a class in a `table` tag due to the support for [using HTML5 data attributes to do it](https://datatables.net/manual/options#HTML-5-data-attributes). Responsive does allow itself to be enabled via a class, but I've actually only kept that for backwards compatibility with itself.

Regarding the ColReorder and Responsive integration. This is indeed a bit on the tricky side - thanks for posting it. It is quite possible to have Responsive's details show/hide control not on the first column - it could be on any column, the whole row, or indeed none if you don't want to view the details.

To that end, it might be appropriate to require that the developer using the two needs to set the `fixedColumnsLeft` (or right, or whatever) as they need?

**Comment by dswitzer** [comment]
Supporting data attributes over CSS would be fine too. I just need a way to trigger it from the markup.

The responsive behavior is problematic, for the reasons you stated.

However since the `ColReorder` doesn't support arbitrary columns to lock down for re-ordering (which makes sense, because you can really only do that on the ends), there are limitations.

For our purposes, the responsive column is always the right most. The code could definitely be modified to find the position of the "responsive" column and only apply if it's on the left/right.

I just didn't need for our usage, but wanted to post it for something to go off of.
